language: php

php:
  #- 7
  #- 7.1
  - 7.2
  #- 7.3

matrix:
  fast_finish: true

env:
  global:
    # Drupal paths.
    - DRUPAL_STAGING_DIR="$HOME/drupal_staging"
    - DRUPAL_PATH="$HOME/drupal8"
    - PATH="$PATH:$DRUPAL_PATH/vendor/bin:$HOME/.composer/vendor/bin"
    - DRUPAL_TEST_RESULTS_DIR="$HOME/drupal_test_results"
    - DRUPAL_TEST_RESULTS_DB="$DRUPAL_TEST_RESULTS_DIR/test_results.sqlite"

    # Testing environment variables.
    - SIMPLETEST_DB=mysql://root:@127.0.0.1/drupal_travis_db#d8t
    - SIMPLETEST_BASE_URL=http://127.0.0.1:8080

    # Suppress deprecation handling.
    #- SYMFONY_DEPRECATIONS_HELPER=disabled

cache:
  directories:
    #- $DRUPAL_STAGING_DIR
    - $HOME/.composer/cache

services:
  - mysql

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  # Remove  XDebug.
  - phpenv config-rm xdebug.ini || true

  # Create the test db.
  - mysql -e 'CREATE DATABASE IF NOT EXISTS drupal_travis_db;'

  # Add a directory for test results SQLite db.
  - mkdir $DRUPAL_TEST_RESULTS_DIR

  # Stage Drupal codebase.
  - |
      if [[ ! -f $DRUPAL_STAGING_DIR/index.php ]]; then
        git clone --depth=5 --branch=8.9.x http://git.drupal.org/project/drupal.git $DRUPAL_STAGING_DIR
        cd $DRUPAL_STAGING_DIR
        composer install --no-progress --no-suggest
        composer require drupal/console symfony/var-dumper:^3 --no-progress --no-suggest
        composer update phpunit/phpunit --with-dependencies --no-progress
      fi

  # Apply Drupal core patches.
  - cd $DRUPAL_STAGING_DIR
  - git apply $TRAVIS_BUILD_DIR/test.patch

  # Copy staged codebase to live.
  - cp -r $DRUPAL_STAGING_DIR/. $DRUPAL_PATH

install:
  - cd $DRUPAL_PATH/core
  - drupal server 127.0.0.1:8080 &
  - sleep 1s

script:
  - cd $DRUPAL_PATH/core
  #- ../vendor/bin/phpunit tests/Drupal/Tests/Core/Access/AccessResultTest.php
  - ../vendor/bin/phpunit --group Template --testsuite=unit
  #- ../vendor/bin/phpunit --testsuite=unit --exclude-group=Annotation
  #- ../vendor/bin/phpunit -v tests/Drupal/KernelTests/Core/Test/TestRunTest.php
  #- ../vendor/bin/phpunit -v modules/simpletest/tests/src/Unit/SimpletestPhpunitRunCommandTest.php
  #- ../vendor/bin/phpunit -v modules/simpletest/tests/src/Kernel/PhpUnitErrorTest.php
  #- ../vendor/bin/phpunit -v modules/simpletest/tests/src/Functional/SimpletestUiTest.php
  #- cd $DRUPAL_PATH
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --color --php $(which php) --url http://127.0.0.1:8080 --types "Simpletest" --all
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --color --php $(which php) --url http://127.0.0.1:8080 --types PHPUnit-Unit --all
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --color --php $(which php) --url http://127.0.0.1:8080 --types PHPUnit-Build --all
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --color --php $(which php) --url http://127.0.0.1:8080 --types PHPUnit-Kernel Database,image,Image
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --php $(which php) --url http://127.0.0.1:8080 Test
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --php $(which php) --url http://127.0.0.1:8080 simpletest
  #- |
  #    if [[ "$TRAVIS_PHP_VERSION" == "7.3" ]]; then
  #      php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --color --php $(which php) --url http://127.0.0.1:8080 --types PHPUnit-Kernel --all
  #    fi
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --php $(which php) --url http://127.0.0.1:8080 --types PHPUnit-Unit Access
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/SimpleTestInstallBatchTest.php
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/TimeZoneTest.php
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/BrokenSetUpTest.php
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --php $(which php) --url http://127.0.0.1:8080 --types PHPUnit-Unit --all
  #- php core/scripts/run-tests.sh --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --clean --php $(which php)

notifications:
  email:
    on_success: never
