language: php

sudo: required

php:
  #- 7
  #- 7.1
  #- 7.2
  #- 7.3
  - 7.4snapshot
  #- nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

env:
  global:
    # Drupal paths.
    - DRUPAL_STAGING_DIR="$HOME/drupal_staging"
    - DRUPAL_PATH="$HOME/drupal8"
    - PATH="$PATH:$DRUPAL_PATH/vendor/bin:$HOME/.composer/vendor/bin"
    - DRUPAL_TEST_RESULTS_DIR="$HOME/drupal_test_results"
    - DRUPAL_TEST_RESULTS_DB="$DRUPAL_TEST_RESULTS_DIR/test_results.sqlite"

    # Testing environment variables.
    - SIMPLETEST_DB=mysql://root:@127.0.0.1/drupal_travis_db#d8txxxxverylong
    - SIMPLETEST_BASE_URL=http://127.0.0.1:8080

    # Suppress deprecation handling.
    #- SYMFONY_DEPRECATIONS_HELPER=disabled

cache:
  directories:
    - $DRUPAL_STAGING_DIR
    - $HOME/.composer/cache
    - $HOME/opt

services:
  - mysql

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:
  # Remove  XDebug.
  - phpenv config-rm xdebug.ini || true

  # Create the test db.
  - mysql -e 'CREATE DATABASE IF NOT EXISTS drupal_travis_db;'

  # Add a directory for test results SQLite db.
  - mkdir $DRUPAL_TEST_RESULTS_DIR
  
  # Stage Drupal codebase.
  - |
      if [[ ! -f $DRUPAL_STAGING_DIR/index.php ]]; then
        git clone --depth=5 http://git.drupal.org/project/drupal.git $DRUPAL_STAGING_DIR
        cd $DRUPAL_STAGING_DIR
        # git checkout 8.8.x
        composer install --no-progress --no-suggest
        # Get Drupal Console.
        composer require drupal/console symfony/var-dumper --no-progress --no-suggest
      fi

  # Copy staged codebase to live.
  - cp -r $DRUPAL_STAGING_DIR/. $DRUPAL_PATH
  - cd $DRUPAL_PATH
  - git apply -v $TRAVIS_BUILD_DIR/test.patch
  - composer update mikey179/vfsstream --with-dependencies --no-progress
  - composer require typo3/phar-stream-wrapper:dev-master --no-progress
  #- composer update phpunit/phpunit symfony/phpunit-bridge phpspec/prophecy symfony/yaml --with-dependencies --no-progress
  
install:
  - cd $DRUPAL_PATH/core
  #- drupal site:install standard $SIMPLETEST_DB --no-interaction
  #- drupal module:install simpletest --verbose --no-interaction
  - drupal server 127.0.0.1:8080 &
  - sleep 4s

script:
  - cd $DRUPAL_PATH/core
  - ../vendor/bin/phpunit --group Database
  #- ../vendor/bin/phpunit -v tests/Drupal/KernelTests/Core/Test/SimpletestTestRunResultsStorageTest.php
  #- ../vendor/bin/phpunit -v modules/simpletest/tests/src/Kernel/PhpUnitErrorTest.php
  #- cd $DRUPAL_PATH
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --php $(which php) --url http://127.0.0.1:8080 Database
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/SimpleTestInstallBatchTest.php
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/TimeZoneTest.php
  #- php core/scripts/run-tests.sh --concurrency $(nproc) --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/BrokenSetUpTest.php
  #- php core/scripts/run-tests.sh --dburl $SIMPLETEST_DB --sqlite $DRUPAL_TEST_RESULTS_DB --clean --php $(which php)

notifications:
  email: false
