language: php

sudo: required

php:
  #- 7
  #- 7.1
  #- 7.2
  - 7.3
  #- 7.4snapshot
  #- nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.4snapshot

env:
  global:
    # Drupal paths.
    - DRUPAL_STAGING_DIR="$HOME/drupal_staging"
    - DRUPAL_PATH="$HOME/drupal8"
    - PATH="$PATH:$DRUPAL_PATH/vendor/bin:$HOME/.composer/vendor/bin"

    # Testing environment variables.
    - SIMPLETEST_DB=mysql://root:@127.0.0.1/drupal_travis_db#d8txxxxverylong
    - SIMPLETEST_BASE_URL=http://127.0.0.1:8080

    # Suppress deprecation handling.
    #- SYMFONY_DEPRECATIONS_HELPER=disabled

cache:
  directories:
    - $DRUPAL_STAGING_DIR
    - $HOME/.composer/cache
    - $HOME/opt

services:
  - mysql

mysql:
  database: drupal_travis_db
  username: root
  encoding: utf8

before_install:

  # Remove  XDebug.
  - phpenv config-rm xdebug.ini || true

  # Stage Drupal codebase.
  - |
      if [[ ! -f $DRUPAL_STAGING_DIR/index.php ]]; then
        git clone --depth=5 http://git.drupal.org/project/drupal.git $DRUPAL_STAGING_DIR
        cd $DRUPAL_STAGING_DIR
        # git checkout 8.8.x
        composer install --no-progress --no-suggest
        # Get Drupal Console.
        composer require drupal/console symfony/var-dumper --no-progress --no-suggest
      fi

  # Copy staged codebase to live.
  - cp -r $DRUPAL_STAGING_DIR/. $DRUPAL_PATH
  - cd $DRUPAL_PATH
  - git apply -v $TRAVIS_BUILD_DIR/test.patch
  #- composer update phpunit/phpunit symfony/phpunit-bridge phpspec/prophecy symfony/yaml --with-dependencies --no-progress
  
install:
  - cd $DRUPAL_PATH/core
  - drupal site:install standard $SIMPLETEST_DB --no-interaction
  - drupal module:install simpletest --verbose --no-interaction
  - drupal server 127.0.0.1:8080 &
  - sleep 4s
  - echo $(nproc)

script:
  - cd $DRUPAL_PATH/core
  #- ../vendor/bin/phpunit --group image,Image
  #- ../vendor/bin/phpunit -v tests/Drupal/KernelTests/Core/Test/SimpletestTestRunResultsStorageTest.php
  #- ../vendor/bin/phpunit -v tests/Drupal/KernelTests/Core/Test/TestRunTest.php
  #- ../vendor/bin/phpunit -v tests/Drupal/FunctionalTests/Bootstrap/UncaughtExceptionTest.php
  #- ../vendor/bin/phpunit -v tests/Drupal/Tests/Core/Test/PhpUnitTestRunnerTest.php
  #- ../vendor/bin/phpunit -v tests/Drupal/KernelTests/Core/Test/PhpUnitTestRunnerTest.php
  #- ../vendor/bin/phpunit -v modules/simpletest/tests/src/Kernel/PhpUnitErrorTest.php
  #- ../vendor/bin/phpunit --version
  - cd $DRUPAL_PATH
  #- ./vendor/bin/paratest -c core/ --colors --bootstrap core/tests/bootstrap.php -p8 --stop-on-failure --testsuite drupal-directories core/tests/
  #- ./vendor/bin/paratest -c core/ --colors --bootstrap core/tests/bootstrap.php -p8 --testsuite unit core/tests/
  #- cd $DRUPAL_PATH/core
  #- ../vendor/bin/phpunit --testsuite unit
  #- ../vendor/bin/phpunit -v tests/Drupal/FunctionalTests/GetTestMethodCallerTest.php
  #- ../vendor/bin/phpunit -v tests/Drupal/Tests/Phpunit4CompatibilityTest.php
  #- ../vendor/bin/phpunit -v modules/aggregator/tests/src/Functional/AggregatorAdminTest.php
  #- ../vendor/bin/phpunit -v modules/block_content/tests/src/Functional/Rest/BlockContentJsonCookieTest.php
  #- ../vendor/bin/phpunit -v modules/file/tests/src/Functional/FileFieldValidateTest.php
  #- ../vendor/bin/phpunit --group Access --testsuite=unit
  #- ../vendor/bin/phpunit -v --testsuite=unit
  #- ../vendor/bin/phpunit -v modules/simpletest/tests/src/Unit/SimpletestPhpunitRunCommandTest.php
  #- ../vendor/bin/phpunit -v modules/taxonomy/tests/src/Functional/Rest/TermXmlAnonTest.php
  #- php core/scripts/run-tests.sh --verbose --color --module simpletest --concurrency $(nproc) --php $(which php) --url http://127.0.0.1:8080
  #- php core/scripts/run-tests.sh --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/image/tests/src/Unit/ImageStyleTest.php
  #- rm core/modules/simpletest/tests/src/Functional/SimpletestUiTest.php
  #- php core/scripts/run-tests.sh --verbose --color --concurrency 16 --php $(which php) --url http://127.0.0.1:8080 simpletest
  - php core/scripts/run-tests.sh --verbose --color --concurrency 16 --php $(which php) --url http://127.0.0.1:8080 Database
  #- php core/scripts/run-tests.sh --verbose --color --concurrency 16 --php $(which php) --url http://127.0.0.1:8080 image,Image
  - php core/scripts/run-tests.sh --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/SimpleTestInstallBatchTest.php
  - php core/scripts/run-tests.sh --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/TimeZoneTest.php
  #- php core/scripts/run-tests.sh --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/tests/Drupal/KernelTests/Core/Test/SimpletestTestRunResultsStorageTest.php
  #- php core/scripts/run-tests.sh --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/tests/Drupal/KernelTests/Core/Test/TestRunTest.php
  - php core/scripts/run-tests.sh --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/BrokenSetUpTest.php
  #- php core/scripts/run-tests.sh --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/SimpleTestTest.php
  #- php core/scripts/run-tests.sh --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/modules/simpletest/src/Tests/KernelTestBaseTest.php
  #- php core/scripts/run-tests.sh --verbose --color --file --php $(which php) --url http://127.0.0.1:8080 core/tests/Drupal/FunctionalTests/Bootstrap/UncaughtExceptionTest.php
  - php core/scripts/run-tests.sh --clean --php $(which php)

notifications:
  email: false
