name: PHPUnit Testing

on:
  push:
    branches: [ test-3350375 ]

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version:
          - "8.1"
        simpletest-db:
          - "mysql://root:@0.0.0.0/drupal_db#d8t"
          - "pgsql://postgres:postgres@localhost/drupal_db#d8t"
          - "sqlite://localhost/test_database#d8t"

    env:
        SIMPLETEST_DB: ${{ matrix.simpletest-db }}

    services:
      mysql:
        image: "mysql:5.7"
        options: >-
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=drupal_db
        ports:
          - "3306:3306"

    steps:

     - name: Setup Postgres database
       if: startsWith(${{ matrix.simpletest-db }}, 'pgsql')
       uses: Daniel-Marynicz/postgresql-action@master
       with:
           postgres_image_tag: 14
           postgres_db: drupal_db
           postgres_extensions: pg_trgm
       
     - name: Postgres extension
       if: startsWith(${{ matrix.php-version }}, 'pgsql')
       run: |
          sudo PGPASSWORD="postgres" -u postgres psql --command="CREATE EXTENSION IF NOT EXISTS pg_trgm;" --dbname=drupal_db --host=localhost

     - name: Install PHP
       uses: "shivammathur/setup-php@v2"
       with:
           php-version: "${{ matrix.php-version }}"
           coverage: "none"
           extensions: "pdo_mysql,pdo_pgsql,gd"
           ini-values: "zend.assertions=1"

     - name: Checkout Drupal
       run: git clone --depth=5 --branch=10.1.x http://git.drupal.org/project/drupal.git .

     - name: Checkout Test
       run: git clone --depth=5 --branch=test-3350375 https://github.com/mondrake/d8-unit.git patch

     - name: 'Patch'
       run: |
          git apply -v patch/test.patch
#          curl https://git.drupalcode.org/project/drupal/-/merge_requests/2129.diff | git apply -v

     - name: Install Composer dependencies
       run: |
          composer install --no-progress --ansi
          composer require drush/drush symfony/config --no-progress --ansi

     - name: Run test
       continue-on-error: true
       run: vendor/bin/phpunit -v -c core --color=always core/tests/Drupal/KernelTests/Core/Database/StatementTest.php
