name: PHPUnit Testing

on:
  push:
    branches: [ test-rector ]

jobs:

#################################

  rector-fu:
    name: "Rector"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:

     - name: Install PHP
       uses: "shivammathur/setup-php@v2"
       with:
           php-version: "${{ matrix.php-version }}"
           coverage: "none"
           ini-values: "zend.assertions=1"

     - name: Checkout Drupal
       run: git clone --depth=5 --branch=11.x http://git.drupal.org/project/drupal.git .

     - name: Checkout Test
       run: git clone --depth=5 --branch=test-rector https://github.com/mondrake/d8-unit.git patch

#     - name: Patch Drupal
#       run: |
#         git apply -v patch/test.patch
#         git apply -v patch/test-phpstan.patch
#          curl https://git.drupalcode.org/project/drupal/-/merge_requests/2691.diff | git apply -v

     - name: Install Composer dependencies
       run: |
          composer install --no-progress --ansi
          composer require rector/rector --no-progress --ansi

#     - name: Run Rector
#       run: |
#          cd core
#          php -d apc.enabled=0 -d apc.enable_cli=0 ../vendor/bin/phpstan analyze lib/Drupal/Core/Database/.
 
#     - uses: actions/upload-artifact@v3
#       with:
#          name: test-results
#          path: sites/simpletest/browser_output
