name: PHPUnit Testing

on:
  push:
    branches: [ test-module ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"
    BROWSERTEST_OUTPUT_DIRECTORY: "sites/default/files/simpletest"
    ZX_DRUPAL_BRANCH: '10.0.x'
    ZX_MODULE_NAME: 'Sophron'
    ZX_MODULE_MACHINE: sophron
    ZX_MODULE_BRANCH: '8.x-1.x' 
    ZX_MODULE_GIT_URL: 'project/sophron.git' 

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04
    env:
        SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

    strategy:
      matrix:
        php-version:
#          - "8.1"
          - "8.2"

    steps:
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: "none"
        extensions: "gd"
        ini-values: "zend.assertions=1"

    - name: Checkout Drupal
      run: git clone --depth=5 --branch=$ZX_DRUPAL_BRANCH http://git.drupal.org/project/drupal.git .

    - name: Checkout Test
      run: git clone --depth=5 --branch=test-module https://github.com/mondrake/d8-unit.git patch
      
    - name: Patch Drupal
      run: curl https://www.drupal.org/files/issues/2022-09-17/3295821-109.patch | git apply -v

    - name: Install Composer dependencies
      run: |
        composer install --no-progress --ansi
        composer run-script drupal-phpunit-upgrade
        composer require drush/drush --no-progress --ansi

    - name: Checkout $ZX_MODULE_NAME
      run: git clone --depth=5 --branch=$ZX_MODULE_BRANCH https://git.drupalcode.org/$ZX_MODULE_GIT_URL $ZX_MODULE_MACHINE_staging

#    - name: Module Patch
#      run: |
#        cd textimage_staging
#        # git apply -v ../patch/test.patch
#        curl https://git.drupalcode.org/project/textimage/-/merge_requests/4.diff | git apply -v

    - name: Composer require $ZX_MODULE_NAME from local staging
      run: |
        git -C $ZX_MODULE_MACHINE_staging checkout -b test-run-branch
        composer config repositories.test-run '{"type": "path", "url": "$ZX_MODULE_MACHINE_staging", "options": {"symlink": false}}'
        composer require "drupal/$ZX_MODULE_MACHINEs:dev-test-run-branch" --no-progress --ansi
    
    - name: Install Drupal
      run: |
        vendor/bin/drush site-install standard --db-url=$SIMPLETEST_DB -y
        vendor/bin/drush runserver localhost:8080 &
        vendor/bin/drush rq
        vendor/bin/drush en $ZX_MODULE_MACHINE -y
        vendor/bin/drush pml --type=module --no-core
        mkdir -p sites/default/files/simpletest

    - name: Run tests
      continue-on-error: true
#      run: vendor/bin/phpunit -c core --color=always modules/contrib/image_effects/tests/src/Functional/SettingsFormTest.php
      run: vendor/bin/phpunit -c core --color=always --group=$ZX_MODULE_MACHINE

    - uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: sites/simpletest/browser_output
          
