name: PHPUnit Testing

on:
  push:
    branches: [ test-rector ]

jobs:

#################################

  rector-fu:
    name: "Rector"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:

     - name: Install PHP
       uses: "shivammathur/setup-php@v2"
       with:
           php-version: "${{ matrix.php-version }}"
           coverage: "none"
           ini-values: "zend.assertions=1"

     - name: Checkout Drupal
       run: git clone --depth=5 --branch=11.x http://git.drupal.org/project/drupal.git .

     - name: Checkout Test
       run: git clone --depth=5 --branch=test-rector https://github.com/mondrake/d8-unit.git patch

     - name: Git config
       run: |
            git config --global user.name 'rector-bot'
            git config --global user.email 'rector-bot@rector-bot.com'

     - name: Rector file
       run: |
         cp patch/rector.php rector.php
         mkdir rector-changes

     - name: Install Composer dependencies
       run: |
          composer install --no-progress --ansi
          composer require rector/rector --no-progress --ansi

     - name: Run Rector
       continue-on-error: true
       run: |
          vendor/bin/rector --version
          vendor/bin/phpcbf --version
          vendor/bin/rector
          vendor/bin/phpcbf --filter=GitModified --standard=SlevomatCodingStandard --sniffs=SlevomatCodingStandard.Namespaces.AlphabeticallySortedUses core
          git diff >rector-changes/rector-changes.patch
#          vendor/bin/phpcs -i 
#          vendor/bin/phpcs --standard=SlevomatCodingStandard -e
 
     - uses: actions/upload-artifact@v3
       with:
          name: rector-changes
          path: rector-changes
