name: PHPUnit Testing

on:
  push:
    branches: [ test-module ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04
    env:
        SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

# SIMPLETEST_DB: "mysql://root:@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "pgsql://postgres:postgres@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

    strategy:
      matrix:
        php-version:
#          - "7.3"
          - "7.4"
#          - "8.0"

#    services:
#      mysql:
#        image: "mysql:5.7"
#        options: >-
#          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
#          -e MYSQL_DATABASE=drupal_db
#        ports:
#          - "3306:3306"
#      postgres:
#        image: "postgres:10.12"
#        env:
#          POSTGRES_PASSWORD: "postgres"
#        options: >-
#          --health-cmd "pg_isready"
#        ports:
#          - "5432:5432"

    steps:
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: "none"
        extensions: "gd"
        ini-values: "zend.assertions=1"

    - name: Checkout Drupal
      run: git clone --depth=5 --branch=9.2.x http://git.drupal.org/project/drupal.git .

    - name: Checkout Test
      run: git clone --depth=5 --branch=test-boh https://github.com/mondrake/d8-unit.git patch
      
    - name: Drupal Patch
      run: curl https://git.drupalcode.org/project/drupal/-/merge_requests/388.diff | git apply -v

    - name: Install Composer dependencies
      run: |
        composer install --no-progress --ansi
        composer run-script drupal-phpunit-upgrade
        composer require drush/drush --no-progress --ansi

    - name: Checkout Pagerer
      run: git clone --depth=5 --branch=8.x-2.x http://git.drupal.org/project/pagerer.git pagerer_staging

    - name: Composer require Pagerer from local staging
      run: |
        git -C pagerer_staging checkout -b test-run-branch
        composer config repositories.test-run '{"type": "path", "url": "pagerer_staging", "options": {"symlink": false}}'
        composer require "drupal/pagerer:dev-test-run-branch" --no-progress --ansi
    
    - name: Install Drupal
      run: |
        vendor/bin/drush site-install standard --db-url=$SIMPLETEST_DB -y
        vendor/bin/drush rq
        vendor/bin/drush en pagerer -y
        vendor/bin/drush runserver localhost:8080 &
        vendor/bin/drush pml --type=module --no-core

    - name: Run tests
      continue-on-error: true
      run: vendor/bin/phpunit -c core --color=always --group Pagerer
