name: PHPUnit Testing

on:
  push:
    branches: [ test-module ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"
    BROWSERTEST_OUTPUT_DIRECTORY: "sites/default/files/simpletest"
    ZX_DRUPAL_BRANCH: '10.0.x'
    ZX_MODULE_NAME: 'Jquery Colorpicker'
    ZX_MODULE_MACHINE: jquery_colorpicker
    ZX_MODULE_STAGING: jquery_colorpicker_staging
    ZX_MODULE_BRANCH: '3310798-implement-a-subscriber' 
    ZX_MODULE_GIT_URL: 'issue/jquery_colorpicker-3310798.git' 

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04
    env:
        SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

    strategy:
      matrix:
        php-version:
          - "8.1"
#          - "8.2"

    steps:
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: "none"
        extensions: "gd"
        ini-values: "zend.assertions=1"

    - name: Checkout Drupal
      run: git clone --depth=5 --branch=${{ env.ZX_DRUPAL_BRANCH }} http://git.drupal.org/project/drupal.git .

    - name: Checkout Test
      run: git clone --depth=5 --branch=test-module https://github.com/mondrake/d8-unit.git patch
      
#    - name: Patch Drupal
#      run: curl https://www.drupal.org/files/issues/2022-09-17/3295821-109.patch | git apply -v

    - name: Install Composer dependencies
      run: |
        composer install --no-progress --ansi
        composer require drush/drush --no-progress --ansi
#        composer require drupal/vendor_stream_wrapper fileeye/linuxlibertine-fonts --ansi

    - name: Checkout ${{ env.ZX_MODULE_NAME }}
      run: git clone --depth=5 --branch=${{ env.ZX_MODULE_BRANCH }} https://git.drupalcode.org/${{ env.ZX_MODULE_GIT_URL }} ${{ env.ZX_MODULE_STAGING }}

#    - name: Module Patch
#      run: |
#        cd textimage_staging
#        # git apply -v ../patch/test.patch
#        curl https://git.drupalcode.org/project/textimage/-/merge_requests/4.diff | git apply -v

    - name: Composer require ${{ env.ZX_MODULE_NAME }} from local staging
      run: |
        git -C ${{ env.ZX_MODULE_STAGING }} checkout -b test-run-branch
        composer config repositories.test-run '{"type": "path", "url": "${{ env.ZX_MODULE_STAGING }}", "options": {"symlink": false}}'
        composer require "drupal/${{ env.ZX_MODULE_MACHINE }}:dev-test-run-branch" --no-progress --ansi
    
    - name: Install Drupal
      run: |
        vendor/bin/drush site-install standard --db-url=$SIMPLETEST_DB -y
        vendor/bin/drush runserver localhost:8080 &
        vendor/bin/drush rq
        vendor/bin/drush en ${{ env.ZX_MODULE_MACHINE }} -y
        vendor/bin/drush pml --type=module --no-core
        mkdir -p sites/default/files/simpletest

    - name: Run tests
      continue-on-error: true
#      run: vendor/bin/phpunit -c core --color=always modules/contrib/image_effects/tests/src/Functional/SettingsFormTest.php
      run: vendor/bin/phpunit -c core --color=always --group=${{ env.ZX_MODULE_MACHINE }}

    - uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: sites/simpletest/browser_output
