name: PHPUnit Testing

on:
  push:
    branches: [ test-phpstan-baseline ]

jobs:
  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:
      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          ini-values: "zend.assertions=1"

      - name: Checkout Drupal
        run: git clone --depth=5 --branch=11.x http://git.drupal.org/project/drupal.git .

      - name: Checkout Test
        run: git clone --depth=5 --branch=test-phpstan-baseline https://github.com/mondrake/d8-unit.git patch
      
      - name: 'Patch'
        run: |
          git apply -v patch/test.patch 
        
      - name: Install Composer dependencies
        run: |
         composer install --no-progress --ansi

      - name: PHPStan scan
        continue-on-error: true
        run: vendor/bin/phpstan -vvv analyse --configuration=./core/phpstan.neon.dist

#      - name: Generate PHPStan baseline
#        run: |
#          cd core
#          ../vendor/bin/phpstan analyze --configuration=phpstan.neon.dist --memory-limit=-1 --generate-baseline=.phpstan-baseline.php
#          git config user.email "a@a.com"
#          git config user.name "Aa Aa"
#          git add .
#          git diff --cached

#      - uses: actions/upload-artifact@v3
#        with:
#          name: baseline
#          path: core/.phpstan-baseline.php
#          include-hidden-files: true
  
