name: PHPUnit Testing

on:
  push:
    branches: [ test-phpstan-baseline ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"
    MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://localhost:4444"]'

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04
    env:
        SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

# SIMPLETEST_DB: "mysql://root:@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "pgsql://postgres:postgres@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:
      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          ini-values: "zend.assertions=1"

      - name: Checkout Drupal
        run: git clone --depth=5 --branch=11.x http://git.drupal.org/project/drupal.git .

      - name: Checkout Test
        run: git clone --depth=5 --branch=test-phpstan-baseline https://github.com/mondrake/d8-unit.git patch
      
      - name: 'Patch'
        run: |
          git apply -v patch/test.patch 
#          curl https://git.drupalcode.org/project/drupal/-/merge_requests/2129.diff | git apply -v
#          curl https://www.drupal.org/files/issues/2022-05-26/3282315-14.patch | git apply -v
        
      - name: Install Composer dependencies
        run: |
         composer install --no-progress --ansi

#      - name: PHPStan scan
#        continue-on-error: true
#        run: |
#          cd core 
#          ../vendor/bin/phpstan analyse

      - name: Generate PHPStan baseline
        run: |
          cd core
          ../vendor/bin/phpstan analyze --configuration=phpstan.neon.dist --memory-limit=-1 --generate-baseline=.phpstan-baseline.php
          git config user.email "a@a.com"
          git config user.name "Aa Aa"
          git add .
          git diff --cached

      - uses: actions/upload-artifact@v3
        with:
          name: baseline
          path: core/.phpstan-baseline.php
          include-hidden-files: true
  
