name: PHPUnit Testing

on:
  push:
    branches: [ test-phpstan-baseline ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"
    MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://localhost:4444"]'

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04
    env:
        SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

# SIMPLETEST_DB: "mysql://root:@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "pgsql://postgres:postgres@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          extensions: "pdo_mysql,pdo_pgsql,gd"
          ini-values: "zend.assertions=1"

      - name: Checkout Drupal
        run: git clone --depth=5 --branch=10.0.x http://git.drupal.org/project/drupal.git .

      - name: Checkout Test
        run: git clone --depth=5 --branch=test-phpstan-baseline https://github.com/mondrake/d8-unit.git patch
      
      - name: 'Patch'
        run: |
          curl https://git.drupalcode.org/project/drupal/-/merge_requests/1794.diff | git apply -v
#          git apply -v patch/test.patch 
        
      - name: Install Composer dependencies
        run: composer install --no-progress --ansi

#      - name: PHPStan scan
#        continue-on-error: true
#        run: |
#          cd core
#          ../vendor/bin/phpstan analyze

      - name: Genereate PHPStan baseline
        continue-on-error: true
        run: |
          cd core
          ../vendor/bin/phpstan analyze --generate-baseline 
          git config user.email "a@a.com"
          git config user.name "Aa Aa"
          git add .
          git diff --cached

      - uses: actions/upload-artifact@v2
        with:
          name: baseline
          path: core/phpstan-baseline.neon
          
