name: PHPUnit Testing

on:
  push:
    branches: [ test-imagemagick ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"
    BROWSERTEST_OUTPUT_DIRECTORY: "sites/default/files/simpletest"
    ZX_DRUPAL_BRANCH: '11.x'
    ZX_MODULE_NAME: 'ImageMagick'
    ZX_MODULE_MACHINE: imagemagick
    ZX_MODULE_STAGING: imagemagick_staging
    ZX_MODULE_BRANCH: '3451489-imagemagick-7-compatibility' 
    ZX_MODULE_GIT_URL: 'issue/imagemagick-3451489.git' 

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04
    env:
        SIMPLETEST_DB: "mysql://root:@0.0.0.0/drupal_db?module=mysql#d8t"

    strategy:
      matrix:
        php-version:
          - "8.3"

    services:
      mysql:
        image: "mysql:8"
        options: >-
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=drupal_db
        ports:
          - "3306:3306" 
    
    steps:
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: "none"
        extensions: "gd"
        ini-values: "zend.assertions=1"

    - name: Checkout Drupal
      run: git clone --depth=5 --branch=${{ env.ZX_DRUPAL_BRANCH }} http://git.drupal.org/project/drupal.git .

    - name: Checkout Test
      run: git clone --depth=5 --branch=test-imagemagick https://github.com/mondrake/d8-unit.git patch
      
#    - name: Patch Drupal
#      run: curl https://www.drupal.org/files/issues/2022-09-23/3295821-112.patch | git apply -v

    - name: Install Composer dependencies
      run: |
        composer install --ansi
        composer require drush/drush --ansi
#        composer require drupal/vendor_stream_wrapper fileeye/linuxlibertine-fonts --ansi

#    - name: 'Patch Symfony'
#      run: |
#         patch -p5 -d vendor/symfony/process <patch/symfony.patch
#         patch -p1 -d vendor/phpunit/phpunit <patch/phpunit.patch

    - name: Checkout ${{ env.ZX_MODULE_NAME }}
      run: git clone --depth=5 --branch=${{ env.ZX_MODULE_BRANCH }} https://git.drupalcode.org/${{ env.ZX_MODULE_GIT_URL }} ${{ env.ZX_MODULE_MACHINE }}_staging

#    - name: Module Patch
#      run: |
#        cd ${{ env.ZX_MODULE_MACHINE }}_staging
#        git apply -v ../patch/test.patch
#        curl https://git.drupalcode.org/project/textimage/-/merge_requests/4.diff | git apply -v

    - name: Composer require ${{ env.ZX_MODULE_NAME }} from local staging
      run: |
        git -C ${{ env.ZX_MODULE_MACHINE }}_staging checkout -b test-run-branch
        composer config repositories.test-run '{"type": "path", "url": "${{ env.ZX_MODULE_MACHINE }}_staging", "options": {"symlink": false}}'
        composer require "drupal/${{ env.ZX_MODULE_MACHINE }}:dev-test-run-branch" --no-progress --ansi
    
#    - name: PHPStan scan
#      continue-on-error: true
#      run: |
#        cd modules/contrib/${{ env.ZX_MODULE_MACHINE }}
#        ../../../vendor/bin/phpstan analyse
#        ../../../vendor/bin/phpstan analyse --generate-baseline 

    - name: Install Drupal
      run: |
        vendor/bin/drush site-install standard --db-url=$SIMPLETEST_DB -y
        vendor/bin/drush runserver localhost:8080 &
        vendor/bin/drush rq
        vendor/bin/drush en ${{ env.ZX_MODULE_MACHINE }} -y
        vendor/bin/drush pml --type=module --no-core
        mkdir -p sites/default/files/simpletest

    - name: Versions
      run: |
        convert -v

    - name: Run tests
      continue-on-error: true
      run: vendor/bin/phpunit -c core --color=always --group=${{ env.ZX_MODULE_MACHINE }}
#      run: vendor/bin/phpunit -c core --color=always modules/contrib/imagemagick/tests/src/Functional/ToolkitImagemagickTest.php

#    - uses: actions/upload-artifact@v2
#      with:
#        name: test-results
#        path: sites/simpletest/browser_output

#    - uses: actions/upload-artifact@v3
#      with:
#        name: baseline
#        path: modules/contrib/${{ env.ZX_MODULE_MACHINE }}/phpstan-baseline.neon
