name: PHPUnit Testing

on:
  push:
    branches: [ test-boh ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-latest
    env:
        SIMPLETEST_DB: "mysql://root:@0.0.0.0/drupal_db#d8t"

    strategy:
      matrix:
        test-args:
          - "--group Database"

    services:
      mysql:
        image: "mysql:5.7"
        options: >-
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=drupal_db
        ports:
          - "3306:3306"

    steps:
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "7.4"
        coverage: "none"
        extensions: "pdo_mysql"
        ini-values: "zend.assertions=1"

    - name: Checkout Drupal
      run: git clone --depth=5 --branch=9.2.x http://git.drupal.org/project/drupal.git .

    - name: Checkout Test
      run: git clone --depth=5 --branch=test-boh https://github.com/mondrake/d8-unit.git patch
      
    - name: Patch for VarDumper
      run: curl https://git.drupalcode.org/project/drupal/-/merge_requests/181.diff | git apply -v

    - name: 'Patch'
      run: git apply -v patch/test.patch

    - name: Install Composer dependencies
      run: |
        composer install --no-progress --ansi
        composer run-script drupal-phpunit-upgrade
        composer require drush/drush --no-progress --ansi

    - name: Install Drupal
      run: |
        vendor/bin/drush site-install standard --db-url=$SIMPLETEST_DB -y
        vendor/bin/drush runserver localhost:8080 &

    - name: Run test a
      run: vendor/bin/phpunit -c core --color=always core/tests/Drupal/KernelTests/Core/Database/SelectExtenderTest.php
      
    - name: Run test b
      run: vendor/bin/phpunit -c core --color=always core/modules/system/tests/src/Functional/Database/SelectPagerDefaultTest.php
      
#    - name: Run test ${{ matrix.test-args }}
#      run: vendor/bin/phpunit -c core --color=always ${{ matrix.test-args }}
#    - name: Run test ${{ matrix.test-args }}
#      run: vendor/bin/phpunit -c core --color=always core/modules/system/src/Kernel/System/InfoAlterTest.php
#    - name: Run test ${{ matrix.test-args }}
#      run: vendor/bin/phpunit -c core --color=always core/modules/field/tests/src/Kernel/DisplayApiTest.php
