name: PHPUnit Testing

on:
  push:
    branches: [ test-phpunit10 ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"
    BROWSERTEST_OUTPUT_DIRECTORY: "/home/runner/work/d8-unit/d8-unit/sites/default/files/simpletest"
    MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://localhost:4444"]'

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04
    env:
        SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

# SIMPLETEST_DB: "mysql://root:@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "pgsql://postgres:postgres@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

    strategy:
      matrix:
        php-version:
          - "8.2"

#    services:
#      mysql:
#        image: "mysql:5.7"
#        options: >-
#          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
#          -e MYSQL_DATABASE=drupal_db
#        ports:
#          - "3306:3306"
#      postgres:
#        image: "postgres:10.12"
#        env:
#          POSTGRES_PASSWORD: "postgres"
#        options: >-
#          --health-cmd "pg_isready"
#        ports:
#          - "5432:5432"

    steps:
#      - name: Install Chrome
#        uses: "browser-actions/setup-chrome@latest"

#      - name: Check Chrome version
#        run: chrome --version

#      - name: Install Chromedriver
#        uses: "nanasess/setup-chromedriver@master"

#      - name: Run Chromedriver
#        run: chromedriver --port=4444 &

      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          extensions: "pdo_mysql,pdo_pgsql,gd"
          ini-values: "zend.assertions=1"

      - name: Checkout Drupal
        run: git clone --depth=5 --branch=11.x http://git.drupal.org/project/drupal.git .

      - name: Checkout Test
        run: git clone --depth=5 --branch=test-phpunit10 https://github.com/mondrake/d8-unit.git patch

      - name: 'Patch'
        run: git apply -v patch/test.patch
#        run: curl https://git.drupalcode.org/project/drupal/-/merge_requests/677.diff | git apply -v
        
      - name: Install Composer dependencies
        continue-on-error: true
        run: |
          composer install --no-progress --ansi
          #composer remove phpunit/phpunit phpspec/prophecy --dev
          #composer require phpunit/phpunit:dev-master --dev --no-progress --ansi --update-with-all-dependencies --ignore-platform-req php
          #composer require phpunit/phpunit:dev-master phpspec/prophecy-phpunit:dev-master --dev --no-progress --ansi --update-with-all-dependencies --ignore-platform-req php
          composer run-script drupal-phpunit-upgrade
          composer require symfony/phpunit-bridge:^6.2 --dev --no-progress --ansi --update-with-all-dependencies
#          vendor/bin/phpunit -v -c core --migrate-configuration

      - name: Patch PHPUnit
        run: curl https://patch-diff.githubusercontent.com/raw/mondrake/phpunit/pull/1.diff | patch -d vendor/phpunit/phpunit -p1
          
      - name: Patch PHPUnit-Bridge
        run: curl https://patch-diff.githubusercontent.com/raw/mondrake/phpunit-bridge/pull/5.diff | patch -d vendor/symfony/phpunit-bridge -p1
          
#      - name: Install Drush
#        run: composer require drush/drush --no-progress --ansi

#      - name: Install Drupal
#        run: |
#          vendor/bin/drush site-install standard --db-url=$SIMPLETEST_DB -y
#          vendor/bin/drush rq
#          vendor/bin/drush runserver localhost:8080 &

#      - name: Run test d
#        continue-on-error: true
#        run: vendor/bin/phpunit -c core --color=always core/modules/image/tests/src/Functional/ImageStylesPathAndUrlTest.php

#      - name: Run test e
#        continue-on-error: true
#        run: vendor/bin/phpunit -c core --color=always core/modules/system/tests/src/Functional/Entity/EntityListBuilderTest.php

      - name: Run test b
        continue-on-error: true
        run: vendor/bin/phpunit -c core --color=always core/tests/Drupal/Tests/Core/Utility/TokenTest.php

      - name: Run test c
        continue-on-error: true
        run: vendor/bin/phpunit -c core --color=always core/tests/Drupal/KernelTests/Core/Asset/DeprecatedAssetsTest.php
