name: PHPUnit Testing

on:
  push:
    branches: [ test-boh ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04
    env:
        SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

# SIMPLETEST_DB: "mysql://root:@0.0.0.0/drupal_db#d8t"

    strategy:
      matrix:
        php-version:
#          - "7.3"
          - "7.4"
#          - "8.0"

#    services:
#      mysql:
#        image: "mysql:5.7"
#        options: >-
#          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
#          -e MYSQL_DATABASE=drupal_db
#        ports:
#          - "3306:3306"

    steps:
    - name: Install PHP
      uses: "shivammathur/setup-php@v2"
      with:
        php-version: "${{ matrix.php-version }}"
        coverage: "none"
        extensions: "pdo_mysql,gd"
        ini-values: "zend.assertions=1"

    - name: Checkout Drupal
      run: git clone --depth=5 --branch=9.2.x http://git.drupal.org/project/drupal.git .

    - name: Checkout Test
      run: git clone --depth=5 --branch=test-boh https://github.com/mondrake/d8-unit.git patch
      
    - name: 'Patch'
      run: git apply -v patch/test.patch

    - name: Install Composer dependencies
      run: |
        composer install --no-progress --ansi
        composer run-script drupal-phpunit-upgrade
        composer require drush/drush --no-progress --ansi

    - name: Install Drupal
      run: |
        vendor/bin/drush site-install standard --db-url=$SIMPLETEST_DB -y
        vendor/bin/drush rq
        vendor/bin/drush runserver localhost:8080 &

    - name: Run tests
      run: vendor/bin/phpunit -c core --color=always core/modules/migrate/tests/src/Unit/MigrateSqlIdMapTest.php
#      run: vendor/bin/phpunit -c core --color=always core/tests/Drupal/KernelTests/Core/Database/BasicSyntaxTest.php
#      run: vendor/bin/phpunit -c core --color=always --group Database
