name: PHPUnit Testing

on:
  push:
    branches: [ test-phpstan-baseline ]

env:
    SIMPLETEST_BASE_URL: "http://localhost:8080"
    MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","chromeOptions":{"args":["--disable-gpu","--headless", "--no-sandbox"]}}, "http://localhost:4444"]'

jobs:

#################################

  test-fu:
    name: "Test"
    runs-on: ubuntu-20.04
    env:
        SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

# SIMPLETEST_DB: "mysql://root:@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "pgsql://postgres:postgres@0.0.0.0/drupal_db#d8t"
# SIMPLETEST_DB: "sqlite://localhost/test_database#d8t"

    strategy:
      matrix:
        php-version:
          - "8.1"

    steps:
      - name: Install PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          extensions: "pdo_mysql,pdo_pgsql,gd"
          ini-values: "zend.assertions=1"

      - name: Checkout Drupal
        run: git clone --depth=5 --branch=10.0.x http://git.drupal.org/project/drupal.git .

      - name: Checkout Test
        run: git clone --depth=5 --branch=test-phpstan-baseline https://github.com/mondrake/d8-unit.git patch
      
      - name: 'Patch'
        run: |
          git apply -v patch/test.patch 
#          curl https://www.drupal.org/files/issues/2022-01-07/3178534-145.patch | git apply -v
        
      - name: Install Composer dependencies
        run: |
          composer install --no-progress --ansi
#          composer run-script drupal-phpunit-upgrade
#          composer require drush/drush --no-progress --ansi
#          php -i
#          vendor/bin/phpunit -v -c core --migrate-configuration
#          git diff

#      - name: Install Drupal
#        run: |
#          vendor/bin/drush site-install standard --db-url=$SIMPLETEST_DB -y
#          vendor/bin/drush rq
#          vendor/bin/drush runserver localhost:8080 &

      - name: Genereate PHPStan baseline
        continue-on-error: true
        run: |
          git config user.email "a@a.com"
          git config user.name "Aa Aa"
          git add .
          git commit -m base
          cd core
          ../vendor/bin/phpstan analyze --generate-baseline 
          cd ..
          git diff
#          ../vendor/bin/phpstan analyze ../composer/Plugin/VendorHardening/VendorHardeningPlugin.php modules/block/tests/src/Kernel/Migrate/d6/MigrateBlockContentTranslationTest.php modules/block/tests/src/Kernel/Migrate/d7/MigrateBlockTest.php modules/system/tests/modules/plugin_test/src/Plugin/plugin_test/fruit/ExtendingNonInstalledClass.php
#          ../vendor/bin/phpstan analyze --generate-baseline

      - uses: actions/upload-artifact@v2
        with:
          name: baseline
          path: core/phpstan-baseline.neon
          
